"""adding last heard column

Revision ID: 3532c3efd9f3
Revises: 7d1a4ef8c2b1
Create Date: 2026-04-03 14:14:55.042039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3532c3efd9f3'
down_revision: Union[str, Sequence[str], None] = '7d1a4ef8c2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('last_heard', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'last_heard')
    # ### end Alembic commands ###
