"""route table changed

Revision ID: f25a91e1701d
Revises: f6c5eb6cd137
Create Date: 2026-03-05 18:47:11.620210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25a91e1701d'
down_revision: Union[str, Sequence[str], None] = 'f6c5eb6cd137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_id', sa.Integer(), nullable=False))
    op.add_column('routes', sa.Column('reporter', sa.LargeBinary(length=4), nullable=True))
    op.add_column('routes', sa.Column('hop_count', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('dest_seq_num', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('timestamp', sa.String(), nullable=True))
    op.drop_index(op.f('ix_routes_sequence_number'), table_name='routes')
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    op.drop_constraint(op.f('routes_source_fkey'), 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'nodes', ['next_hop'], ['id'])
    op.create_foreign_key(None, 'routes', 'nodes', ['reporter'], ['id'])
    op.drop_column('routes', 'sequence_number')
    op.drop_column('routes', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('source', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('sequence_number', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key(op.f('routes_source_fkey'), 'routes', 'nodes', ['source'], ['id'])
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.create_index(op.f('ix_routes_sequence_number'), 'routes', ['sequence_number'], unique=False)
    op.drop_column('routes', 'timestamp')
    op.drop_column('routes', 'dest_seq_num')
    op.drop_column('routes', 'hop_count')
    op.drop_column('routes', 'reporter')
    op.drop_column('routes', 'route_id')
    # ### end Alembic commands ###
